### ISSUE TITLE
【view】動画の置き場所を決める

### ISSUE THREAD

**Issue by pompom0c0** [manma-co/manma-co.github.io#31]
動画を短縮再生してトップにするのが1番効果が高いと思います。
動画が届き次第議論ですね。

参考サイト
https://life-is-tech.com/

**Comment by hidetomasuoka** [comment]
このやり方だと音声どうしようかな。。。
いきなり動いて音が出るとね。。。

**Comment by hidetomasuoka** [comment]
https://life-is-tech.com/ は、gif なので、参考サイトにしない

**Comment by hidetomasuoka** [comment]
http://airintern.com/
これとかどうだろう？
