### ISSUE TITLE
【design】Changing the main image

### ISSUE THREAD

**Issue by honda-misaki** [manma-co/manma-co.github.io#4]
## WHAT
1. 構図の変更
2. 画像にタイトルを入れる
3. 画像の縦サイズを小さくし、下にmanmaか家族留学の簡単なキャッチコピーを入れる
(例:彩々顕微)
![12952964_1313921585290515_522488937_o](https://cloud.githubusercontent.com/assets/6498450/14270606/b64b5096-fb2a-11e5-843b-9de691105e0d.jpg)
(manma)
![12953179_1313921711957169_431572508_o](https://cloud.githubusercontent.com/assets/6498450/14270618/d41992f4-fb2a-11e5-8ca1-0b0069e68a20.jpg)

## WHY
1. mobile版だとトリミングが、雑な感じに見えるから
2. 何のサイトかファーストビューでユーザーに伝えるため
3. サイトの目的をファーストビューで伝えるため

**Comment by hidetomasuoka** [comment]
PCだと横幅4:3もしくは16:9が主流ですが、Mobileだと縦長が主流かと思います。
別サイトをデザインする勢いで、つくらないと厳しい気がしています。
スマホ最適化は、どうするか決めないといけないですね
