### ISSUE TITLE
【view】Past projects view

### ISSUE THREAD

**Issue by pompom0c0** [manma-co/manma-co.github.io#9]
## WHAT

過去のプロジェクトを表示するviewを作成する
## WHY

manmaの家族留学以外のプロジェクトを知ってもらうため

**Comment by hidetomasuoka** [comment]
issueは二つにわけたほうがいいかな

見た目と、クリックしたら過去のProjectが紹介されるのはレベル感がちょっと違う

**Comment by honda-misaki** [comment]
そうですね...2つ突っ込んでいました><
分けます。

**Comment by honda-misaki** [comment]
@hidetomasuoka 記事の共有ありがとうございます。
費用対効果が低いので優先度下げました。他のタスク優先にします。

忘備録：http://qiita.com/naru0504/items/58011181f2c271808c7f#%E6%A6%82%E8%A6%81%E3%81%BF%E3%81%9F%E3%81%84%E3%81%AA

**Comment by hidetomasuoka** [comment]
ちょー細かい指摘ですが、
備忘録？
http://www.ninjal.ac.jp/publication/catalogue/kokken_mado/36/01/

**Comment by honda-misaki** [comment]
( ﾟдﾟ)ﾊｯ!
