### ISSUE TITLE
topページファーストビューの画像修正

### ISSUE THREAD

**Issue by pompom0c0** [manma-co/manma-co.github.io#95]
## what
- 画像の解像度を落とす
- 文字を画像に入れるのではなく、上に載せるようにする
- 高さを変更する(高くして、いろはさん・はるかさんの顔も入るようにする)
## why
- 読み込みに時間がかかっているから
- 写真変更時にIllustratorで文字を入れ直す作業が無駄だから
- headerの背景が透明からピンクになるよう、変更できたから

**Comment by pompom0c0** [comment]
@hidetomasuoka 
こちら改善案が3つありまして、どれを対応しようか迷っています。
1. 今の写真のまま、解像度を落としたものを使用する
一旦これをするべきですか？
2. 写真を新しいものに変える
Instagram用に桃子さんが写真をたくさん用意してくださっているのでこちらを使用する
https://www.instagram.com/manma.co/
3. 家族留学動画をgifにしたものを使用する
gif作ってみました。これを使用するのが1番家族留学の雰囲気が伝わり、最善だと思うのですが、ピンクのフレームがブラウザ幅によっては変な位置に来てしまうのと、スマホ対応どうしよう...って感じです。
https://drive.google.com/open?id=0B177n-cCddycdFpSQU1lZFpzMm8

**Comment by pompom0c0** [comment]
こちらの件、今ももこさんに相談しています。
来週の土曜までにどの対応をするか決めるつもりです。

**Comment by hidetomasuoka** [comment]
とりあえず、WP対応との兼ね合いで決めましょう
江原さん、篠原君、美咲さん、舛岡の時間等分量で決めましょう。
とにかく目的が手段にならないように

**Comment by pompom0c0** [comment]
了解です。
